[audio]
enabled = true
volume-master = 1
volume-regular = 1
volume-ui = 1
volume-ambient = 1
volume-music = 1

[display]
width = 1280
height = 720
samples = 0
framerate = -1
fullscreen = false
limit-fps-iconified = false

[camera]
sensitivity = 2
fov = 90
fov-effects = true
shaking = true
inertia = true

[chunks]
load-distance = 22
load-speed = 4
padding = 2

[graphics]
fog-curve = 1
backlight = false
dense-render = true
gamma = 1
frustum-culling = true
skybox-resolution = 96
chunk-max-vertices = 200000
chunk-max-vertices-dense = 800000
chunk-max-renderers = 6
advanced-render = true
ssao = true
shadows-quality = 3
dense-render-distance = 56

[ui]
language = "ru_RU"
world-preview-size = 64

[debug]
generator-test-mode = false
do-write-lights = true

