[mountains]
parameters = [
    {weight=1, value=0.2},
    {weight=0.8, value=0.3}
]
layers = [
    {below-sea-level=false, height=1, block="base:grass_block"},
    {below-sea-level=false, height=3, block="base:dirt"},
    {height=-1, block="base:stone"},
    {height=1, block="base:bazalt"}
]
sea-layers = [
    {height=-1, block="base:water"}
]
plant-chance = 0.2
plants = [
    {weight=1, block="base:grass"},
    {weight=0.01, block="base:flower"}
]
structure-chance = 0.01
structures = [
    {name="tree0", weight=1},
    {name="tree1", weight=1}
]

[high_mountains]
parameters = [
    {weight=1, value=0.8},
    {weight=0.6, value=0.4}
]
layers = [
    {below-sea-level=false, height=1, block="base:stone"},
    {height=-1, block="base:stone"},
    {height=1, block="base:bazalt"}
]
sea-layers = [
    {height=-1, block="base:water"}
]
plant-chance = 0.05
plants = [
    {weight=1, block="base:grass"}
]
structure-chance = 0.001
structures = [
    {name="tree0", weight=1}
]

[valleys]
parameters = [
    {weight=1, value=0.0},
    {weight=0.9, value=0.1}
]
layers = [
    {below-sea-level=false, height=1, block="base:grass_block"},
    {below-sea-level=false, height=5, block="base:dirt"},
    {height=-1, block="base:stone"},
    {height=1, block="base:bazalt"}
]
sea-layers = [
    {height=-1, block="base:water"}
]
plant-chance = 0.6
plants = [
    {weight=1, block="base:grass"},
    {weight=0.05, block="base:flower"}
]
structure-chance = 0.05
structures = [
    {name="tree0", weight=1},
    {name="tree1", weight=1},
    {name="tree2", weight=1}
]

[river_valleys]
parameters = [
    {weight=1, value=0.0},
    {weight=0.7, value=0.0}
]
layers = [
    {below-sea-level=false, height=1, block="base:sand"},
    {below-sea-level=false, height=3, block="base:dirt"},
    {height=-1, block="base:stone"},
    {height=1, block="base:bazalt"}
]
sea-layers = [
    {height=-1, block="base:water"}
]
plant-chance = 0.3
plants = [
    {weight=1, block="base:grass"},
    {weight=0.02, block="base:flower"}
]
structure-chance = 0.02
structures = [
    {name="tree0", weight=1},
    {name="tree1", weight=1}
] 