name: Build HaipX for Windows

on:
  push:
    branches: [ main, 0.28 ]
  pull_request:
    branches: [ main, 0.28 ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1
      
    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.25.0'
        
    - name: Install dependencies
      run: |
        # Устанавливаем Chocolatey
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
        
        # Устанавливаем необходимые пакеты
        choco install ninja -y
        choco install vcpkg -y
        
        # Устанавливаем библиотеки через vcpkg
        vcpkg install glfw3:x64-windows
        vcpkg install glew:x64-windows
        vcpkg install glm:x64-windows
        
    - name: Setup vcpkg environment
      run: |
        $env:VCPKG_ROOT = "C:\vcpkg"
        $env:PATH = "$env:VCPKG_ROOT;$env:PATH"
        
    - name: Build HaipX for Windows
      run: |
        mkdir build-windows
        cd build-windows
        cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake ..
        ninja
        
    - name: Upload Windows build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: haipx-windows-build
        path: |
          build-windows/HaipX.exe
          build-windows/res/
        retention-days: 30 