name: Build (DISABLED)

on:
  # workflow_dispatch:
  # push:
  #   branches: [ 0.28 ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: This workflow is disabled
      run: |
        echo "This workflow is disabled. Use Ultra Simple Windows Build instead."
        exit 1
