name: Single File Build Test (DISABLED)

# on:
  # workflow_dispatch:
  # push:
  #   branches: [ 0.28 ]

jobs:
  test-single-file:
    runs-on: windows-latest
    
    steps:
    - name: This workflow is disabled
      run: |
        echo "This workflow is disabled. Use Simple Windows Build instead."
        exit 1 